### ISSUE TITLE
[Burger Order Page] Custom Burger

### ISSUE THREAD

**Issue by hereiskeith** [WendyChenj/burger-queen#3]
- [x] [ UI ] A price box at the side   
- [x] [ UI ] Click the burger and sandwitch button can switch UI to it.
- [x] [ UI ] Click the ingredient will add or decrease the number of ingredient
- [x] [ UI ] Set the min number of ingredient to 0 and max number of ingredient to 3 
- [x] [ UI ] total price is being calculated based on the number of ingredient 
- [x] [ store ] Fetch ingredient from api & initial price

**Comment by WendyChenj** [comment]
- [ ]
